[tools]
uv = "latest"

[env]
PROJECT_NAME = "{{ config_root | basename }}"
_.python.venv = { path = ".venv", create = true }

[tasks.install]
description = "Install dependencies"
run = """
uv sync
uv lock
uv pip install -e .
"""

[tasks.test]
description = "Run tests"
run = "pytest tests/"

[tasks.format]
description = "Format the code"
run = """
echo "Running isort"
isort .
echo "Running ruff check..."
ruff check --fix
echo "Running ruff format..."
ruff format
echo ""
echo "Running json-format..."
python3 json-format.py .
"""

[tasks.info]
description = "Print project information"
run = """
echo "Project: $PROJECT_NAME"
echo "Virtual Environment: $VIRTUAL_ENV"
"""